version: '3.8'
services:
  bank-webhook:
    image: bank-webhook-image
    container_name: bank-webhook-container
    ports:
      - "3005:3005"

  hdfcDummyApi:
    image: hdfc-dummy-api-image
    container_name: hdfc-dummy-api-container
    ports:
      - "3004:3004"
    environment:
      - CONTAINER_NAME=bank-webhook-container
    depends_on:
      - bank-webhook
  
  user-app:
    image: user-app-image
    container_name: user-app-container
    ports:
      - "3001:3000"