name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/user-app/Dockerfile
        push: true
        tags: anmolban/user-app  # Replace with your Docker Hub username and repository

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/bank-webhook/Dockerfile
        push: true
        tags: anmolban/bank-webhook
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/hdfc-bank-dummy-api/Dockerfile
        push: true
        tags: anmolban/hdfc-bank-dummy-api

    - name: Verify Pushed Image
      run: docker pull anmolban/user-app  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull anmolban/bank-webhook
    
    - name: Verify Pushed Image
      run: docker pull anmolban/hdfc-bank-dummy-api

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull anmolban/user-app:latest
          sudo docker stop user-app || true
          sudo docker rm user-app || true
          sudo docker run -d -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} --name user-app -p 3005:3000 anmolban/user-app:latest
          
          sudo docker pull anmolban/hdfc-bank-dummy-api:latest
          sudo docker stop hdfc-bank-dummy-api || true
          sudo docker rm hdfc-bank-dummy-api || true
          sudo docker run -d -e SECRET=${{ secrets.SECRET }} -e DATABASE_URL=${{secrets.DATABASE_URL}} -e CONTAINER_NAME=${{secrets.CONTAINER_NAME}} --name hdfc-bank-dummy-api -p 3004:3004 anmolban/hdfc-bank-dummy-api:latest

          sudo docker pull anmolban/bank-webhook:latest
          sudo docker stop bank-webhook || true
          sudo docker rm bank-webhook || true
          sudo docker run -d -e DATABASE_URL=${{secrets.DATABASE_URL}} -e HDFC_SECRET=${{secrets.HDFC_SECRET}} --name bank-webhook-container -p 3005:3005 anmolban/bank-webhook:latest

